departments <- c(
  "311",
  "animal shelter",
  "ce commercial",
  "city attorney",
  "code enforcement",
  "construction inspection",
  "drain maintenance",
  "engineering",
  "environmental enforcement",
  "environmental maintenance",
  "fire services",
  "flood control",
  "general services",
  "grounds maintenance",
  "heavy equipment services",
  "housing community development",
  "library",
  "parks and neighborhoods",
  "police services",
  "shelby county",
  "solid waste management",
  "speed humps",
  "storm water",
  "street maintenance",
  "traffic signals",
  "traffic signs"
  )

ce_columns <- c(
  "division",
  "department",
  "group_name",
  "category",
  "ce_category",
  "request_type",
  "incident_type_id",
  "incident_number",
  "incident_id",
  "resolution_code",
  "resolution_code_meaning",
  "resolution_summary",
  "summary_1",
  "request_status",
  "request_priority",
  "creation_date",
  "reported_date",
  "last_modified_date",
  "last_update_date",
  "followup_date",
  "close_date",
  "incident_resolved_date",
  "next_open_task_date",
  "sr_creation_channel",
  "created_by",
  "created_by_user",
  "owner_name",
  "number_of_tasks",
  "last_update_login",
  "last_updated_by",
  "mlgw_status",
  "mlgw_on",
  "parcel_id",
  "street_name",
  "full_address",
  "location_1",
  "address1",
  "address2",
  "address3",
  "city",
  "state",
  "postal_code",
  "district",
  "sub_district",
  "map_page",
  "target_block",
  "zone",
  "area",
  # "location1",
  "collection_day",
  "swm_code"
)
